---
# handlers file for esiedge.dhcp-server
- name: restart the dhcp service
  service:
          name: "{{dhcp_service}}"
          state: restarted
          enabled: yes
- name: reload firewalld
  shell:
          cmd: firewall-cmd --reload

